/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcReplacementRateInputs {
    'socket': string;
  }
  interface AgcReplacementRateInputsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcReplacementRateProgress {
    'socket': string;
  }
  interface AgcReplacementRateProgressAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcReplacementRateResultsPlaceholder {}
  interface AgcReplacementRateResultsPlaceholderAttributes extends StencilHTMLAttributes {}

  interface AgcReplacementRateResults {
    'socket': string;
  }
  interface AgcReplacementRateResultsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcReplacementRate {
    'mode': 'full' | 'step';
    'socket': string;
    'tract': string;
  }
  interface AgcReplacementRateAttributes extends StencilHTMLAttributes {
    'mode'?: 'full' | 'step';
    'onAgcCalculated'?: (event: CustomEvent) => void;
    'onAgcStepChanged'?: (event: CustomEvent) => void;
    'socket'?: string;
    'tract'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgcReplacementRateInputs': Components.AgcReplacementRateInputs;
    'AgcReplacementRateProgress': Components.AgcReplacementRateProgress;
    'AgcReplacementRateResultsPlaceholder': Components.AgcReplacementRateResultsPlaceholder;
    'AgcReplacementRateResults': Components.AgcReplacementRateResults;
    'AgcReplacementRate': Components.AgcReplacementRate;
  }

  interface StencilIntrinsicElements {
    'agc-replacement-rate-inputs': Components.AgcReplacementRateInputsAttributes;
    'agc-replacement-rate-progress': Components.AgcReplacementRateProgressAttributes;
    'agc-replacement-rate-results-placeholder': Components.AgcReplacementRateResultsPlaceholderAttributes;
    'agc-replacement-rate-results': Components.AgcReplacementRateResultsAttributes;
    'agc-replacement-rate': Components.AgcReplacementRateAttributes;
  }


  interface HTMLAgcReplacementRateInputsElement extends Components.AgcReplacementRateInputs, HTMLStencilElement {}
  var HTMLAgcReplacementRateInputsElement: {
    prototype: HTMLAgcReplacementRateInputsElement;
    new (): HTMLAgcReplacementRateInputsElement;
  };

  interface HTMLAgcReplacementRateProgressElement extends Components.AgcReplacementRateProgress, HTMLStencilElement {}
  var HTMLAgcReplacementRateProgressElement: {
    prototype: HTMLAgcReplacementRateProgressElement;
    new (): HTMLAgcReplacementRateProgressElement;
  };

  interface HTMLAgcReplacementRateResultsPlaceholderElement extends Components.AgcReplacementRateResultsPlaceholder, HTMLStencilElement {}
  var HTMLAgcReplacementRateResultsPlaceholderElement: {
    prototype: HTMLAgcReplacementRateResultsPlaceholderElement;
    new (): HTMLAgcReplacementRateResultsPlaceholderElement;
  };

  interface HTMLAgcReplacementRateResultsElement extends Components.AgcReplacementRateResults, HTMLStencilElement {}
  var HTMLAgcReplacementRateResultsElement: {
    prototype: HTMLAgcReplacementRateResultsElement;
    new (): HTMLAgcReplacementRateResultsElement;
  };

  interface HTMLAgcReplacementRateElement extends Components.AgcReplacementRate, HTMLStencilElement {}
  var HTMLAgcReplacementRateElement: {
    prototype: HTMLAgcReplacementRateElement;
    new (): HTMLAgcReplacementRateElement;
  };

  interface HTMLElementTagNameMap {
    'agc-replacement-rate-inputs': HTMLAgcReplacementRateInputsElement
    'agc-replacement-rate-progress': HTMLAgcReplacementRateProgressElement
    'agc-replacement-rate-results-placeholder': HTMLAgcReplacementRateResultsPlaceholderElement
    'agc-replacement-rate-results': HTMLAgcReplacementRateResultsElement
    'agc-replacement-rate': HTMLAgcReplacementRateElement
  }

  interface ElementTagNameMap {
    'agc-replacement-rate-inputs': HTMLAgcReplacementRateInputsElement;
    'agc-replacement-rate-progress': HTMLAgcReplacementRateProgressElement;
    'agc-replacement-rate-results-placeholder': HTMLAgcReplacementRateResultsPlaceholderElement;
    'agc-replacement-rate-results': HTMLAgcReplacementRateResultsElement;
    'agc-replacement-rate': HTMLAgcReplacementRateElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
